// 3D circuit geometry generated by scripts/extract-circuit-geometry.py
// from FastF1 fastest-lap position telemetry. See that script's docstring
// for field semantics.

/** Affine transform from raw F1 positional-stream coordinates (meters) into
 *  the normalized geometry space. Lets live OpenF1 location data map onto the
 *  3D track with no runtime alignment detection. */
export interface GpsTransform {
  /** Official map rotation applied, degrees */
  rotationDeg: number;
  /** Center subtracted after rotation, meters (rotated frame) */
  center: [number, number];
  /** Meters per normalized unit (half the larger bbox extent) */
  scale: number;
  /** Pre-rotation bbox of source telemetry, meters: [minX, maxX, minY, maxY].
   *  Used at runtime to auto-detect a decimeter-vs-meter unit mismatch. */
  rawBounds: [number, number, number, number];
  /** Manual alignment nudge, normalized units */
  offset: [number, number];
  /** Manual scale correction, default 1 */
  scaleAdjust: number;
}

export interface CircuitGeometry {
  id: string;
  /** 240 uniform points along the lap: [x, y, z]. x/y in [-1, 1] (y up,
   *  official map orientation); z meters above the track's lowest point. */
  pts: [number, number, number][];
  /** Lap length, km */
  len: number;
  /** Total elevation change, m */
  elev: number;
  /** Measured S1/S2 sector boundaries as lap fractions, or null */
  sectors: [number, number] | null;
  /** [label, lapFraction] from FastF1 circuit info — fallback/validation only;
   *  runtime corner chips prefer CircuitData.corners (hand-calibrated + metadata) */
  corners: [string, number][];
  transform: GpsTransform;
  source: string;
}
